name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm test
      - name: Validate
        run: npx zapier-platform validate
        env:
          ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}
      - name: Send Build Alert
        uses: apialerts/notify-action@v2
        with:
          api_key: ${{ secrets.APIALERTS_API_KEY }}
          event: ci.integration.build.zapier
          channel: developer
          message: 'zapier - PR build success'
          tags: CI/CD,Zapier,Build
          link: ${{ format('{0}/{1}/actions/runs/{2}', github.server_url, github.repository, github.run_id) }}
